<?php
/*
Plugin Name: Easy Custom Auto Excerpt
Plugin URI: http://www.tonjoo.com/easy-custom-auto-excerpt/
Description: Auto Excerpt for your post on home, search and archive.
Version: 1.0.7
Author: Todi Adiyatmo Wijoyo
Author URI:  http://todiadiyatmo.com
*/

function tonjoo_ecae_plugin_loaded() {

	load_plugin_textdomain( 'easy-custom-auto-excerpt', false,  dirname( plugin_basename( __FILE__ ) ).'/languages' ); 


}
add_action('plugins_loaded', 'tonjoo_ecae_plugin_loaded');

$plugin = plugin_basename(__FILE__); 
add_filter("plugin_action_links_$plugin", 'tonjoo_ecae_donate' );

function tonjoo_ecae_donate($links) { 
	$donate_link = '<a href="http://tonjoo.com/donate/">Donate</a>'; 
	array_unshift($links, $donate_link); 
	return $links; 
}

add_filter( 'the_content', 'tonjoo_ecae_execute',1 );

function tonjoo_ecae_execute($content,$width=400){

	//ambil options dari db
	$options = get_option('tonjoo_ecae_options');

	$options = tonjoo_ecae_load_default($options);



	$width=$options['width'];
	$justify=$options['justify'];
	
	if($options['home']=="yes" && is_home()){
		return tonjoo_ecae_excerpt($content, $width,$justify);
	}

	if($options['archive']=="yes" && is_archive()){
		return tonjoo_ecae_excerpt($content, $width,$justify);
	}
	
	if($options['search']=="yes" && is_search()){
		return tonjoo_ecae_excerpt($content, $width,$justify);
	}
	
	else {
		return $content;
	}
	
}


function tonjoo_ecae_excerpt($content, $width, $justify) {

	$options = get_option('tonjoo_ecae_options');
	$options = tonjoo_ecae_load_default($options);
	global $post;



	$pos=strpos($post->post_content, '<!--more-->');

	if($options['strip_shortcode']=='yes'){
		$content = strip_shortcodes($content);
	}

	//if read more
	if($pos){
		$content = substr($content, 0, $pos);
	}
	elseif($post->post_excerpt!=''){
		$content =  $post->post_excerpt;
	}
	elseif(!(strlen($content) <= (int) $width) ) {
		
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';
		echo 'asd';

	}

	return "<!-- Generated by Easy Custom Auto Excerpt -->$content";
}


class eace_content_regex{
	var $key;
	var $holder;
	var $regex;
	var $unique_char;

	public function __construct($unique_char,$regex){

		$this->regex = $regex;
		$this->unique_char = $unique_char;
	}

	public function replace(&$content,&$width,$number=false){
		//get all image in the content	
		preg_match_all($this->regex, $content,$this->holder,PREG_PATTERN_ORDER );

		$this->key = 0;



		//only cut bellow the $number variabel treshold ( to limit the number of replacing)
		if($number)
			array_slice($this->holder[0],0,$number);


		foreach ($this->holder[0] as $img) {


			$content = str_replace($img,"{$this->unique_char}{$this->key}{$this->unique_char}", $content);
			$this->key = $this->key+1;



		}	

		//calculate the extra character need for the excerpt to work properly
		$width = $width+$this->key*5;


	}
	function restore(&$content,$maximal=false){
		//maximal number to restore
		if(!$maximal)
			$maximal = $this->key;

		//serves as counter, how many replace are made
		$i=0;

		for($i;$i<$maximal;$i++){
			if(isset($this->holder[0][$i]))
				$content =  str_replace("{$this->unique_char}{$i}{$this->unique_char}", $this->holder[0][$i], $content);
		}

		return $i;
	}

	function remove(&$content){

		$content = preg_replace($this->regex,"" ,$content);
	}
}


require_once( plugin_dir_path( __FILE__ ) . 'tonjoo-library.php');
require_once( plugin_dir_path( __FILE__ ) . 'default.php');
//load option page
require_once( plugin_dir_path( __FILE__ ) . 'options-page.php');